-- Implementando Base de Datos en SQL

-- VERIFICAR QUE LA BASE DE DATOS NO ESTÉ CREADA DELO CONTRARIO LA ELIMINA
IF DB_ID('DBRESERVA') IS NOT NULL
BEGIN
	USE MASTER
	DROP DATABASE DBRESERVA
END
-- CREAR LA BASE DE DATOS EN BLANCO
CREATE DATABASE DBRESERVA
-- GUARDAR LOS TIPOS DE ARCHIVOS: LOG Y PRIMARY
ON PRIMARY (
	-- ARCHIVO PRIMARIO
	NAME='DBRESERVA_MDF', -- NOMBRE
	FILENAME='C:\Dbreserva\DBRESERVA.MDF', -- DIRECTORIO DONDE QUEDARÁ GUARDADO
	SIZE=15MB, -- TAMAÑO INICIAL
	MAXSIZE=250MB, -- TAMAÑO DEL ARCHIVO
	FILEGROWTH=10MB -- INCREMENTO DEL ARCHIVO
),(
	-- ARCHIVO SECUNDARIO
	NAME='DBRESERVA_NDF', -- NOMBRE
	FILENAME='C:\Dbreserva\DBRESERVA.NDF', -- DIRECTORIO DONDE QUEDARÁ GUARDADO
	SIZE=15MB, -- TAMAÑO INICIAL
	MAXSIZE=UNLIMITED, -- TAMAÑO MAXIMO DEL ARCHIVO
	FILEGROWTH=10MB -- INCREMENTO DEL ARCHIVO
)
-- ARCHIVO LOG
LOG ON (
	NAME='DBRESERVA_LDF', -- NOMBRE
	FILENAME='C:\Dbreserva\DBRESERVA.LDF', -- DIRECTORIO DONDE QUEDARÁ GUARDADO
	SIZE=15MB, -- TAMAÑO INICIAL
	MAXSIZE=500MB, -- TAMAÑO MAXIMO DEL ARCHIVO
	FILEGROWTH=10% -- INCREMENTO DEL ARCHIVO
)
GO

--ACTIVAR LA BASE DE DATOS
USE DBRESERVA




